name: AynaLivePlayerWinBuild

on: workflow_dispatch


jobs:
  params:
    runs-on: windows-latest
    outputs:
      params: ${{ steps.env-vars.outputs.params }}
    steps:
      - name: Generate cache_id
        run: |
          if [ "${{ github.event.inputs.cache_id }}" ] ; then
            echo "cache_id=${{ github.event.inputs.cache_id }}" >> $GITHUB_ENV
          else
            echo "cache_id=$(echo $RANDOM | md5sum | head -c 20)" >> $GITHUB_ENV
          fi
      - id: script
        uses: actions/github-script@v6
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: 'AynaLivePlayer',
              repo: 'AynaLivePlayer',
              ref: `master`
            })
            core.exportVariable('sha', String(commit.data.sha))
            
      - id: env-vars
        name: Output environment variables
        run: echo "::set-output name=params::$(echo $(jq -n 'env'))"
  build:
    runs-on: windows-latest
    needs: params
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            git
            mingw-w64-x86_64-go
            mingw-w64-x86_64-mpv
            zip
          
      - uses: actions/checkout@v3
        with: 
          repository: AynaLivePlayer/AynaLivePlayer
          ref: master

      - name: Install Fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Build
        run:  fyne package --src $(pwd)/app/gui --name AynaLivePlayer.exe --appVersion 0.8.4 --icon ../../assets/icon.jpg
      
      - name: Add Dll
        run: cp /bin/mpv-1.dll $(pwd)/app/gui/mpv-1.dll
      
      - name: Add zip
        run: zip -j app/gui/AynaLivePlayer${{}}.zip app/gui/AynaLivePlayer.exe app/gui/mpv-1.dll
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path:
            app/gui/AynaLivePlayer.zip

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/gui/AynaLivePlayer.zip"
          commit: version
          name: "AynaLivePlayer ${{ env.long_time }}"
          body: "**AynaLivePlayer Git commit**: https://github.com/AynaLivePlayer/AynaLivePlayer/commit/${{ fromJson(needs.params.outputs.params).sha }}\n**Build Time**: ${{ env.long_time }}\n**Build Details**: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          tag: "${{ env.short_time }}"
          allowUpdates: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}